// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.fr');

goog.require('Blockly.Msg');

Blockly.Msg["ADD_COMMENT"] = "Bakisa commentaire";
Blockly.Msg["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "Okoki ko longola variable te '%1' Po esalami po na ba fonction '%2'";
Blockly.Msg["CHANGE_VALUE_TITLE"] = "Modifier la valeur :";
Blockly.Msg["CLEAN_UP"] = "Ko longola ba blocs nioso";
Blockly.Msg["COLLAPSE_ALL"] = "Ko diminuer ba blocs";
Blockly.Msg["COLLAPSE_BLOCK"] = "Réduire le bloc";
Blockly.Msg["COLOUR_BLEND_COLOUR1"] = "couleur 1";
Blockly.Msg["COLOUR_BLEND_COLOUR2"] = "couleur 2";
Blockly.Msg["COLOUR_BLEND_HELPURL"] = "http://meyerweb.com/eric/tools/color-blend/";
Blockly.Msg["COLOUR_BLEND_RATIO"] = "taux";
Blockly.Msg["COLOUR_BLEND_TITLE"] = "Sangisa";
Blockly.Msg["COLOUR_BLEND_TOOLTIP"] = "Sangisa ba couleur na intervalle oyo ezo kende (de 0.0 ti na 1.0).";
Blockly.Msg["COLOUR_PICKER_HELPURL"] = "https://fr.wikipedia.org/wiki/Couleur";
Blockly.Msg["COLOUR_PICKER_TOOLTIP"] = "Pona couleur na kati ya palette.";
Blockly.Msg["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
Blockly.Msg["COLOUR_RANDOM_TITLE"] = "couleur aléatoire";
Blockly.Msg["COLOUR_RANDOM_TOOLTIP"] = "Pona couleur na hasard.";
Blockly.Msg["COLOUR_RGB_BLUE"] = "bleu";
Blockly.Msg["COLOUR_RGB_GREEN"] = "vert";
Blockly.Msg["COLOUR_RGB_HELPURL"] = "http://www.december.com/html/spec/colorper.html";
Blockly.Msg["COLOUR_RGB_RED"] = "rouge";
Blockly.Msg["COLOUR_RGB_TITLE"] = "colorier en";
Blockly.Msg["COLOUR_RGB_TOOLTIP"] = "sala couleur moko na quantité spécifiée na rouge, vert na bleu. Ba valeurs na kati ya 0 na 100.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "longola ba boucle";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "ko kende na itération ya boucle oyo elandi";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "Ko bima ya boucle principale (ya liboso)";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "Ko sauter boucle oyo,pe ko salela boucle elandi.";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_WARNING"] = "Keba : epekisami ko salela bloc oyo na libanda ya boucle.";
Blockly.Msg["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg["CONTROLS_FOREACH_TITLE"] = "pona element %1 na kati ya liste %2";
Blockly.Msg["CONTROLS_FOREACH_TOOLTIP"] = "Pona element moko na moko ya liste, valeur ya élément ezwi oyo ya variable '%1', pona ko exécuter ba instructions.";
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg["CONTROLS_FOR_TITLE"] = "Pona na %1 ezo kende de %2 ti na %3 après valeur ya iboso,changer pas na %4";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "Ko pesa na variable « %1 » ba valeurs oyo ebandeli na nombre ya libosos ti na nombre ya suka, tango tozo changer valeur ya pas, ko exécuter ba instructions spécifiées.";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "Bakisa condition moko na bloc soki.";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "Bakisa condition ya suka na bloc soki.";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "Bakisa, longola to bongisa ba sections pona ko reconfigurer bloc -soki- oyo.";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "soki te";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "soki pe te";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "soki";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "soki valeur eza ya solo, kasi exécuter na ordre.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "soki valeur moko eza ya solo, kasi eko executer . soki te, exécuter bloc elandi.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "soki valeur ya liboso eza ya solo, kasi exécuter bloc ya liboso. soki te, soki ya mibale eza ya solo, exécuter bloc ya mibale.";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "soki valeur ya liboso eza ya solo, kasi exécuter bloc ya liboso. soki te, soki ya mibale eza ya solo, exécuter bloc ya mibale. soki valeur moko te eza ya solo, exécuter bloc ya suka.";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "http://fr.wikipedia.org/wiki/Boucle_for";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "sala";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = "bandela %1 fois";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "Exécuter ba instructions mbala mingi.";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "Bandela ti";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "Bandela tango";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "Tango valeur eza ya solo te, kasi exécuter ba instructions.";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "Tango valeur eza ya solo, kasi exécuter ba instructions.";
Blockly.Msg["DELETE_ALL_BLOCKS"] = "Ko longola ba %1 blocs ?";
Blockly.Msg["DELETE_BLOCK"] = "Ko longola bloc";
Blockly.Msg["DELETE_VARIABLE"] = "Ko longola variable '%1'";
Blockly.Msg["DELETE_VARIABLE_CONFIRMATION"] = "Ko longola %1 po na ko salela variable oyo '%2' ?";
Blockly.Msg["DELETE_X_BLOCKS"] = "Ko longola %1 blocs";
Blockly.Msg["DISABLE_BLOCK"] = "Ko désactiver bloc oyo";
Blockly.Msg["DUPLICATE_BLOCK"] = "Ko reproduire";
Blockly.Msg["ENABLE_BLOCK"] = "Ko activer bloc oyo";
Blockly.Msg["EXPAND_ALL"] = "Ko développer ba blocs";
Blockly.Msg["EXPAND_BLOCK"] = "Ko développer bloc oyo";
Blockly.Msg["EXTERNAL_INPUTS"] = "ba entrées externes";
Blockly.Msg["HELP"] = "Sunga";
Blockly.Msg["INLINE_INPUTS"] = "ba entrées na ligne";
Blockly.Msg["IOS_CANCEL"] = "Annuler";
Blockly.Msg["IOS_ERROR"] = "Erreur";
Blockly.Msg["IOS_OK"] = "OK";
Blockly.Msg["IOS_PROCEDURES_ADD_INPUT"] = "+ ko bakisa  entré moko na ordres oyo ba autoriser";
Blockly.Msg["IOS_PROCEDURES_DUPLICATE_INPUTS_ERROR"] = "Cette fonction a des entrées dupliquées.";
Blockly.Msg["IOS_PROCEDURES_INPUTS"] = "ENTRÉES";
Blockly.Msg["IOS_VARIABLES_ADD_BUTTON"] = "+ ko bakisa variable moko";
Blockly.Msg["IOS_VARIABLES_DELETE_BUTTON"] = "Supprimer";
Blockly.Msg["IOS_VARIABLES_EMPTY_NAME_ERROR"] = "Vous ne pouvez pas utiliser un nom de variable vide.";
Blockly.Msg["IOS_VARIABLES_RENAME_BUTTON"] = "Renommer";
Blockly.Msg["IOS_VARIABLES_VARIABLE_NAME"] = "Nom ya variable";
Blockly.Msg["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg["LISTS_CREATE_EMPTY_TITLE"] = "Ko sala liste vide";
Blockly.Msg["LISTS_CREATE_EMPTY_TOOLTIP"] = "Ko zongisa liste moko, ya taille 0, liste eza nga ba enregistrements";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "liste";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "Ko bakisa, ko longola, to ko bongisa ba sections pona ko reconfigurer bloc ya liste oyo.";
Blockly.Msg["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "Ko sala liste moko na";
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "Ko bakisa élément moko na liste.";
Blockly.Msg["LISTS_CREATE_WITH_TOOLTIP"] = "Ko sala liste moko na nombre quelconque d’éléments.";
Blockly.Msg["LISTS_GET_INDEX_FIRST"] = "ya liboso";
Blockly.Msg["LISTS_GET_INDEX_FROM_END"] = "# ko banda na suka";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "#";  // untranslated
Blockly.Msg["LISTS_GET_INDEX_GET"] = "Ko zwa";
Blockly.Msg["LISTS_GET_INDEX_GET_REMOVE"] = "Ko zwa na ko longola";
Blockly.Msg["LISTS_GET_INDEX_LAST"] = "ya suka";
Blockly.Msg["LISTS_GET_INDEX_RANDOM"] = "aléatoire";
Blockly.Msg["LISTS_GET_INDEX_REMOVE"] = "ko longola";
Blockly.Msg["LISTS_GET_INDEX_TAIL"] = "";  // untranslated
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "Ko zongisa élément ya liboso na kati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "Ko zongisa élément na position oyo elakisami na kati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "Ko zongisa élément ya suka na kati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "Ko zongisa élément  hasard na kati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "Ko longola na ko zongisa élément ya liboso na kati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "Ko longola na ko zongisa élément ya position oyo elakisami na kati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "Ko longola na ko zongisa élément ya suka na kati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "Ko longola na ko zongisa élément au hasard nakati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "Ko longola élément ya libosa na kati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "Ko longola élément ya position elakisami na kati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "Ko longola élément ya suka na kati ya liste.";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "Ko longola élément au hasard na kati ya liste.";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_END"] = "ti na # ko banda na suka";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_START"] = "ti na #";
Blockly.Msg["LISTS_GET_SUBLIST_END_LAST"] = "ti na suka";
Blockly.Msg["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_START_FIRST"] = "ko zwa sous-liste ko banda na ebandeli";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_END"] = "ko zwa sous-liste banda # ko banda na suka";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_START"] = "ko zwa sous-liste banda #";
Blockly.Msg["LISTS_GET_SUBLIST_TAIL"] = "";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_TOOLTIP"] = "ko sala copie ya partie oyo eza spécifiée na liste.";
Blockly.Msg["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1 élément ya suka.";
Blockly.Msg["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1 élément ya liboso.";
Blockly.Msg["LISTS_INDEX_OF_FIRST"] = "ko mona occurrence ya liboso ya élément";
Blockly.Msg["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg["LISTS_INDEX_OF_LAST"] = "ko mona occurrence ya suka ya l’élément";
Blockly.Msg["LISTS_INDEX_OF_TOOLTIP"] = "ko zongisa index ya occurrence ya liboso to ya suka ya élément na kati ya liste. ko zongisa %1 soki élément emonani te.";
Blockly.Msg["LISTS_INLIST"] = "na kati ya liste";
Blockly.Msg["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg["LISTS_ISEMPTY_TITLE"] = "%1 ezangi eloko";
Blockly.Msg["LISTS_ISEMPTY_TOOLTIP"] = "Ko zongisa ya solo soki liste ezangi eloko.";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg["LISTS_LENGTH_TITLE"] = "taille ya %1";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "ko zongisa taille ya liste.";
Blockly.Msg["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg["LISTS_REPEAT_TITLE"] = "ko sala liste moko na élément %1 ko bandela %2 fois";
Blockly.Msg["LISTS_REPEAT_TOOLTIP"] = "ko sala liste moko oyo eko salema po na valeur epesami na ko bandela na mbula oyo elakisami.";
Blockly.Msg["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";
Blockly.Msg["LISTS_REVERSE_MESSAGE0"] = "ko balusa %1";
Blockly.Msg["LISTS_REVERSE_TOOLTIP"] = "ko balusa copie ya liste.";
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_INPUT_TO"] = "neti";
Blockly.Msg["LISTS_SET_INDEX_INSERT"] = "ko bakisa neti";
Blockly.Msg["LISTS_SET_INDEX_SET"] = "ko tia";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "ko tia élément na ebandelia ya liste.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "Ko tia élément na position oyo elakisami na kati ya liste.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "ko bakisa élément na suka ya liste.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "ko tia élément na hasard na kati ya liste.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "ko pona élément ya liboso, na kati ya liste.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "ko actualiser élément na position oyo elakisami na liste moko.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "ko pona élément ya suka na liste moko.";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "ko pona élément au hasard na liste moko.";
Blockly.Msg["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg["LISTS_SORT_ORDER_ASCENDING"] = "ko banda na oyo ya mikie ti na oyo ya milayi";
Blockly.Msg["LISTS_SORT_ORDER_DESCENDING"] = "ko banda na oyo ya milayi ti na oyo ya mikie";
Blockly.Msg["LISTS_SORT_TITLE"] = "ko bongisa na ordre %1 %2 %3";
Blockly.Msg["LISTS_SORT_TOOLTIP"] = "ko bongisa lipasa ya liste.";
Blockly.Msg["LISTS_SORT_TYPE_IGNORECASE"] = "alphabétique, ko kipe taille ya ba texte te";
Blockly.Msg["LISTS_SORT_TYPE_NUMERIC"] = "numérique";
Blockly.Msg["LISTS_SORT_TYPE_TEXT"] = "alphabétique";
Blockly.Msg["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg["LISTS_SPLIT_LIST_FROM_TEXT"] = "ko sala liste moko banda ebandeli ya texte";
Blockly.Msg["LISTS_SPLIT_TEXT_FROM_LIST"] = "ko sala texte moko banda ebandela ya liste";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_JOIN"] = "ko sangisa liste moko ya ba textes po ekoma se moko, ko kabola bango na séparateur moko.";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_SPLIT"] = "ko kata texte moko po ekoma liste ya ba textes, ko kabola na separateur moko na moko.";
Blockly.Msg["LISTS_SPLIT_WITH_DELIMITER"] = "na séparateur";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "ya solo te";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "ko zongisa ya solo to ya solo te.";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "ya solo";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://fr.wikipedia.org/wiki/Inegalite_(mathematiques)";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "ko zongisa ya solo soki ba entrées mibale eza sé moko.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "ko zongisa ya solo soki entrée ya liboso eleki oyo elandi na minene.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "ko zongisa ya solo soki entrée ya liboso eleki to eza se moko na oyo elandi.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "ko zongisa ya solo soki entrée ya liboso eleki mikie par rapport ya oyo elandi.";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "ko zongisa ya solo soki entrée ya liboso eleki mikie to eza sé moko na oyo elandi";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "ko zongisa ya solo soki ba entrées mibale ekokani te.";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "ko bakisa %1";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "eko zongisa ya solo soki entrée eza ya solo te. eko zongisa ya solo te soki entrée eza ya solo.";
Blockly.Msg["LOGIC_NULL"] = "eloko te";
Blockly.Msg["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";
Blockly.Msg["LOGIC_NULL_TOOLTIP"] = "eko zongisa eloko te.";
Blockly.Msg["LOGIC_OPERATION_AND"] = "NA";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg["LOGIC_OPERATION_OR"] = "TO";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "ko zongisa ya solo soki ba entrées mibale eza ya solo.";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "ko zongisa ya solo soki to ata na entrée moko oyo eza ya solo.";
Blockly.Msg["LOGIC_TERNARY_CONDITION"] = "MEKA";
Blockly.Msg["LOGIC_TERNARY_HELPURL"] = "https://en.wikipedia.org/wiki/%3F:";
Blockly.Msg["LOGIC_TERNARY_IF_FALSE"] = "soki ya solo te";
Blockly.Msg["LOGIC_TERNARY_IF_TRUE"] = "soki ya solo";
Blockly.Msg["LOGIC_TERNARY_TOOLTIP"] = "ko vérifier condition na kati ya 'MEKA'. soki eza ya solo, eko zongisa valeur 'soki ya solo' ; soki te eko zongisa valeur 'soki ya solo te'.";
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "https://fr.wikipedia.org/wiki/Arithmetique";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "Eko zongisa somme ya ba nombres mibale.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "Eko zongisa quotient ya ba nombres mibale.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "Eko zongisa différence ya ba nombres mibale.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "Eko zongisa produit ya ba nombres mibale.";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "Eko zongisa nombre ya liboso oyo to matisi na puissance ya oyo elandi.";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg["MATH_CHANGE_TITLE"] = "to matisa %1 na %2";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "ko bakisa nombre moko na variable '%1'.";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "Eko zongisa constante oyo o salelaka trop : π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), ou ∞ (infini).";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "ko fixer %1 na kati kati ya %2 na %3";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "ko fixer nombre moko po ezala na ba limites eponami (incluses).";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";  // untranslated
Blockly.Msg["MATH_IS_DIVISIBLE_BY"] = "ekoki ko zala divisible na";
Blockly.Msg["MATH_IS_EVEN"] = "eza pair";
Blockly.Msg["MATH_IS_NEGATIVE"] = "eza négatif";
Blockly.Msg["MATH_IS_ODD"] = "eza impair";
Blockly.Msg["MATH_IS_POSITIVE"] = "eza positif";
Blockly.Msg["MATH_IS_PRIME"] = "eza nombre premier";
Blockly.Msg["MATH_IS_TOOLTIP"] = "ko vérifier soki nombre moko eza pair, impair, premier, entier, positif, négatif, to soki eza divisible na nombre moko particulier. Eko zongisa ya solo to ya solo te.";
Blockly.Msg["MATH_IS_WHOLE"] = "eza entier";
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg["MATH_MODULO_TITLE"] = "reste ya %1 ÷ %2";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "ko zongisa reste ya division euclidienne ya ba nombres mibale.";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "×";  // untranslated
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://fr.wikipedia.org/wiki/Nombre";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "Nombre moko.";
Blockly.Msg["MATH_ONLIST_HELPURL"] = "";  // untranslated
Blockly.Msg["MATH_ONLIST_OPERATOR_AVERAGE"] = "moyenne ya liste";
Blockly.Msg["MATH_ONLIST_OPERATOR_MAX"] = "maximum ya liste";
Blockly.Msg["MATH_ONLIST_OPERATOR_MEDIAN"] = "médiane ya liste";
Blockly.Msg["MATH_ONLIST_OPERATOR_MIN"] = "minimum ya liste";
Blockly.Msg["MATH_ONLIST_OPERATOR_MODE"] = "majoritaires ya liste";
Blockly.Msg["MATH_ONLIST_OPERATOR_RANDOM"] = "élément aléatoire ya liste";
Blockly.Msg["MATH_ONLIST_OPERATOR_STD_DEV"] = "écart-type ya liste";
Blockly.Msg["MATH_ONLIST_OPERATOR_SUM"] = "somme ya liste";
Blockly.Msg["MATH_ONLIST_TOOLTIP_AVERAGE"] = "ko zongisa moyenne (arithmétique) ya ba valeurs numériques na kati ya liste.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MAX"] = "ko zongisa nombre oyo eleki ba mususu na minene na kati ya liste.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MEDIAN"] = "ko zongisa nombre médian ya liste.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MIN"] = "ko zongisa nombre oyo eleki ba mususu na mikie na kati ya liste.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MODE"] = "ko zongisa liste moko ya ba élément(s) oyo ba salelaka trop na kati ya liste.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_RANDOM"] = "ko zongisa élément moko na kati ya liste, oyo eponami o hasard.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_STD_DEV"] = "ko zongisa écart-type ya liste.";
Blockly.Msg["MATH_ONLIST_TOOLTIP_SUM"] = "ko zongisa somme ya ba nombres nioso na kati ya liste.";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";  // untranslated
Blockly.Msg["MATH_RANDOM_FLOAT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "fraction aléatoire";
Blockly.Msg["MATH_RANDOM_FLOAT_TOOLTIP"] = "ko zongisa fraction aléatoire moko na kati kati ya 0.0 (inclus) na 1.0 (exclus).";
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = "entier aléatoire na kati kati ya %1 na %2";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "ko zongisa entier moko aléatoire na kati kati ya ba limites mibale elakisami, incluses.";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "kobongisa ba nombre oyo eza na virgule";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "ko kitisa nombre oyo eza avant virgule";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "ko matisa nombre oyo eza après virgule";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "ko bongisa nombre na ndenge ya ko matisa to ko kitisa valeur oyo eza avant virgule.";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://fr.wikipedia.org/wiki/Racine_carree";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "valeur absolue";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "racine carrée";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "Eko zongisa valeur absolue ya nombre moko.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "Eko zongisa e na puissance ya nombre moko.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "Eko zongisa logarithme naturel ya nombre moko.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "Eko zongisa logarithme na base 10 ya nombre moko.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "Eko zongisa opposé ya nombre moko";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "Eko zongisa 10 na puissance ya nombre moko.";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "Eko zongisa racine carrée ya nombre moko.";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";  // untranslated
Blockly.Msg["MATH_TRIG_ACOS"] = "acos";  // untranslated
Blockly.Msg["MATH_TRIG_ASIN"] = "asin";  // untranslated
Blockly.Msg["MATH_TRIG_ATAN"] = "atan";  // untranslated
Blockly.Msg["MATH_TRIG_COS"] = "cos";  // untranslated
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg["MATH_TRIG_SIN"] = "sin";  // untranslated
Blockly.Msg["MATH_TRIG_TAN"] = "tan";  // untranslated
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "Eko zongisa arccosinus ya nombre moko.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "Eko zongisa arcsinus ya nombre moko.";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "Eko zongisa arctangente ya nombre moko.";
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "Eko zongisa cosinus ya angle moko na degrés (na radians te).";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "Eko zongisa sinus ya angle moko na degrés (na radians te).";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "Eko zongisa tangente ya angle moko na degrés (na radians te).";
Blockly.Msg["NEW_VARIABLE"] = "Ko sala variable...";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "Kombo ya sika po na variable :";
Blockly.Msg["ORDINAL_NUMBER_SUFFIX"] = "";  // untranslated
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "ko pekisa ba ordres te";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "na :";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://fr.wikipedia.org/wiki/Sous-programme";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "ko exécuter fonction '%1' esalama epayi ya utilisateur.";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://fr.wikipedia.org/wiki/Sous-programme";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = "ko exécuter fonction '%1' esalama epayi ya utilisateur pe ko salela résultat na ngo.";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "na :";
Blockly.Msg["PROCEDURES_CREATE_DO"] = "ko sala ya sika '%1'";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "ko definir fonction oyo…";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "ko sala eloko";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "po na";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "ko sala fonction moko oyo ebimisaka eloko moko te.";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://en.wikipedia.org/wiki/Subroutine";  // untranslated
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "ko zonga";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "ko sala fonction moko oyo ebimisaka eloko moko.";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "Keba : fonction oyo eza na ba paramètres mibale.";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "ko surligner définition ya fonction";
Blockly.Msg["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg["PROCEDURES_IFRETURN_TOOLTIP"] = "soki valeur moko eza ya solo, kasi eko zongisa valeur ya mibale.";
Blockly.Msg["PROCEDURES_IFRETURN_WARNING"] = "Keba : bloc oyo esalemi kaka pona définition ya fonction.";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "kombo ya entrée :";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "ko bakisa entré moko na fonction.";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "ba entrées";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "ko bakisa,ko longola moko na ko bongisa ba entrées ya fonction oyo.";
Blockly.Msg["PROCEDURE_ALREADY_EXISTS"] = "procédure ozo benga '%1' ezali dejà.";
Blockly.Msg["REDO"] = "Ko bandela";
Blockly.Msg["REMOVE_COMMENT"] = "ko longola commentaire moko";
Blockly.Msg["RENAME_VARIABLE"] = "ko pesa kombo ya sika na variable…";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "ko pesa ba kombo ya sika na ba variables « %1 » na :";
Blockly.Msg["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_APPEND_TITLE"] = "ko bakisa texte  moko %2 à %1";
Blockly.Msg["TEXT_APPEND_TOOLTIP"] = "ko bakisa texte  moko na variable '%1'.";
Blockly.Msg["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "na minuscules";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "Majuscule na ebandeli ya ba mots nioso";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "na MAJUSCULES";
Blockly.Msg["TEXT_CHANGECASE_TOOLTIP"] = "ko zongisa lipasa ya texte moko na esika mususu.";
Blockly.Msg["TEXT_CHARAT_FIRST"] = "Ko zwa lettre ya liboso";
Blockly.Msg["TEXT_CHARAT_FROM_END"] = "Ko zwa lettre # ko banda na suka";
Blockly.Msg["TEXT_CHARAT_FROM_START"] = "Ko zwa lettre #";
Blockly.Msg["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg["TEXT_CHARAT_LAST"] = "Ko zwa lettre ya suka";
Blockly.Msg["TEXT_CHARAT_RANDOM"] = "Ko zwa lettre moko kaka boye";
Blockly.Msg["TEXT_CHARAT_TAIL"] = "";  // untranslated
Blockly.Msg["TEXT_CHARAT_TITLE"] = "na kati ya text %1 %2";
Blockly.Msg["TEXT_CHARAT_TOOLTIP"] = "Eko zongisa lettre moko esika elakisami.";
Blockly.Msg["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";
Blockly.Msg["TEXT_COUNT_MESSAGE0"] = "nombre %1 likolo ya %2";
Blockly.Msg["TEXT_COUNT_TOOLTIP"] = "ko compter mbalaboni texte moko epasama ezo monana na kati ya texte mususu.";
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "ko bakisa élément moko na texte.";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "ko sangisa";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "ko bakisa,ko longola moko to ko bongisa ba sections pona ko reconfigurer bloc ya texte oyo.";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_END"] = "ti na lettre # ko banda na suka";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_START"] = "ti na lettre #";
Blockly.Msg["TEXT_GET_SUBSTRING_END_LAST"] = "ti na lettre ya suka";
Blockly.Msg["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "na kati yatexte";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FIRST"] = "Ko zwa sous-chaîne ko banda na lettre ya liboso";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_END"] = "Ko zwa sous-chaîne ko banda na lettre # ko banda na suka";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_START"] = "Ko zwa sous-chaîne ko banda na lettre #";
Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"] = "";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_TOOLTIP"] = "Eko zongisa partie oyo eponi na kati ya texte.";
Blockly.Msg["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg["TEXT_INDEXOF_OPERATOR_FIRST"] = "ko mona lipasa ya liboso ya chaîne";
Blockly.Msg["TEXT_INDEXOF_OPERATOR_LAST"] = "ko mona lipasa ya suka occurrence ya chaîne";
Blockly.Msg["TEXT_INDEXOF_TITLE"] = "na kati ya texte %1 %2 %3";
Blockly.Msg["TEXT_INDEXOF_TOOLTIP"] = "Eko zongisa index ya occurrence ya liboso to ya suka ya chaîne ya liboso na kati ya oyo ya mibale. Eko zongisa %1 soki chaîne e monani te.";
Blockly.Msg["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg["TEXT_ISEMPTY_TITLE"] = "%1 eloko moko te eza";
Blockly.Msg["TEXT_ISEMPTY_TOOLTIP"] = "Eko zongisa ya solo soki texte ba pesi ezangi eloko.";
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "ko sala texte ya sika na avec";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "ko sala morceau ya texte tango  tozo pesa nombre moko kaka boye ya ba éléments.";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_LENGTH_TITLE"] = "taille ya %1";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "Eko zongisa nombre ya ba lettres (espaces pe eseparaka bango) na kati ya texte epesami.";
Blockly.Msg["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg["TEXT_PRINT_TITLE"] = "lakisa %1";
Blockly.Msg["TEXT_PRINT_TOOLTIP"] = "lakisa texte, nombre to valeur mususu elakisami.";
Blockly.Msg["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg["TEXT_PROMPT_TOOLTIP_NUMBER"] = "Ko tuna na utilisateur a kotisa nombre moko.";
Blockly.Msg["TEXT_PROMPT_TOOLTIP_TEXT"] = "Ko tuna na utilisateur a kotisa texte moko.";
Blockly.Msg["TEXT_PROMPT_TYPE_NUMBER"] = "Ko tuna po na ko kotisa nombre na message moko pene pene";
Blockly.Msg["TEXT_PROMPT_TYPE_TEXT"] = "Ko tuna po na ko kotisa texte na message moko pene pene";
Blockly.Msg["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";
Blockly.Msg["TEXT_REPLACE_MESSAGE0"] = "Ko longola %1 ko tia %2 na kati ya %3";
Blockly.Msg["TEXT_REPLACE_TOOLTIP"] = "ko longola ba occurrences nioso ya texte moko pona texte mususu.";
Blockly.Msg["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";
Blockly.Msg["TEXT_REVERSE_MESSAGE0"] = "ko balusa %1";
Blockly.Msg["TEXT_REVERSE_TOOLTIP"] = "ko balusa ordre ya ba caractères na kati ya texte.";
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "lettre moko, mot moko to ligne ya texte moko.";
Blockly.Msg["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg["TEXT_TRIM_OPERATOR_BOTH"] = "ko longola ba espaces na ba côtés mibale";
Blockly.Msg["TEXT_TRIM_OPERATOR_LEFT"] = "ko longola ba espaces na côté ya mibali";
Blockly.Msg["TEXT_TRIM_OPERATOR_RIGHT"] = "ko longola ba espaces na côté ya mwasi";
Blockly.Msg["TEXT_TRIM_TOOLTIP"] = "ko zongisa lipasa ya texte na ba espaces elongwe esika moko to mibale.";
Blockly.Msg["TODAY"] = "Lelo";
Blockly.Msg["UNDO"] = "Ekufeli";
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "élément";
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "Ko sala ko 'pona %1'";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "Eko zongisa valeur ya variable oyo.";
Blockly.Msg["VARIABLES_SET"] = "pesa na %1 valeur %2";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "ko sala 'Ko zwa %1'";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "Ko pona variable oyo po eza neti valeur oyo ba kotisi.";
Blockly.Msg["VARIABLE_ALREADY_EXISTS"] = "variable moko ebangami '%1' ezalaka déjà.";
Blockly.Msg["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "Variable oyo ebangami '%1' esalema déjà po na ba variable musus ya type '%2'.";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;

Blockly.Msg["MATH_HUE"] = "230";
Blockly.Msg["LOOPS_HUE"] = "120";
Blockly.Msg["LISTS_HUE"] = "260";
Blockly.Msg["LOGIC_HUE"] = "210";
Blockly.Msg["VARIABLES_HUE"] = "330";
Blockly.Msg["TEXTS_HUE"] = "160";
Blockly.Msg["PROCEDURES_HUE"] = "290";
Blockly.Msg["COLOUR_HUE"] = "20";